src/config/routes.rb
Rails.application.routes.draw do
  
  root to: "homepage#index"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'homepage/index', to: 'homepage#index', as: 'homepage' 

  get 'studentpage/index', to: 'studentpage#index', as: 'studentpage'

  get 'tutorpage/index', to: 'tutorpage#index', as: 'tutorpage'

  get 'post/list', to: 'post#list', as: 'list'
  get 'post/new', to: 'post#new', as: 'new'
  post 'post/create'
  patch 'post/update'
  get 'post/list'
  get 'post/show'
  get 'post/edit'
  get 'post/delete'
  get 'post/update'
  
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/post.rb
class Post < ApplicationRecord
end

src/app/models/subject.rb
class Subject < ApplicationRecord
end

src/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

src/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    def index
    end
end

src/app/controllers/loginpage_controller.rb
class LoginpageController < ApplicationController
    ## Tests the login feature
    before_action :authenticate_user!
    def index
    end
end

src/app/controllers/post_controller.rb
class PostController < ApplicationController
    ## Methods for posts

    ## Lists all posts from the 'posts' db
    def list
        @posts = Post.all
    end
    
    ## Lists only on post from 'posts' db
    def show
        @post = Post.find(params[:id])
    end
    
    ## Creates new post and a corresponding subject
    def new
        @post = Post.new
        @subjects = Subject.all
    end
    
    ## Adds inputs to 'posts' db
    def create
        @post = Post.new(post_params)
	
        if @post.save
            redirect_to :action => 'studentpage/index'
        else
            @subjects = Subject.all
            render :action => 'new'
        end
    end
    
    ## Edit post (for tutor feature)
    def edit
        @post = Post.find(params[:id])
        @subjects = Subject.all
    end
    
    ## Takes in parameters to edit post (for tutor feature)
    def update
        @post = Post.find(params[:id])
	
        if @post.update_attributes(post_param)
            redirect_to :action => 'show', :id => @post
        else
            @subjects = Subject.all
            render :action => 'edit'
        end
    end

    ## Takes in input parameters
    def post_params
        params.require(:posts).permit(:title, :entry, :subject, :post_id)
    end
    
    ## Delete post from 'posts' db (for tutor feature)
    def delete
        Post.find(params[:id]).destroy
        redirect_to :action => 'list'
    end

    ## Display subject from 'subjects' db (for subjects page)
    def show_subjects
        @subject = Subject.find(params[:id])
     end

end

src/app/controllers/studentpage_controller.rb
class StudentpageController < ApplicationController
    ## Asks user to sign in before accessing student's page
    before_action :authenticate_user!
    def index
    end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/post_helper.rb
module PostHelper
end

src/app/views/homepage/_navbar.html.erb
<!-- homepage nav bar, contains sign in button -->

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Sign In', studentpage_path,  :class => "btn btn-default btn-lg" %>
    </div>
  </div>
</nav>

src/app/views/homepage/index.html.erb
<!-- displays home page nav bar-->
<%= render "navbar" %>

<div class = "container">
    <!-- logo format -->
    <div class = "wrap-hp-logo row center-block">
        <img class="img-responsive" src="https://user-images.githubusercontent.com/45517485/100167033-1787b180-2e8c-11eb-8a41-2e16720c0c63.png">
    </div>
    
    <!-- about web application statement format -->
    <div class = "row">
        <div class = "col-md-8 col-md-offset-2 text-center">
            <h1>
            About LEO
            </h1>
            <p class="hero-copy typography-quote-reduced">
            LEO is a platform meant to host and provide the 
            tools for effective online tutorship and mentorship. 
            This web application allows students to post questions 
            and receive responses from dedicated college tutors. 
            Students can use this resource to receive chemistry 
            tutorship or mentorship for succeeding in their academic 
            aspirations.
            </p>
        </div>
    </div>

    <!-- Mission statement format -->
    <div class = "row">
        <div class = "col-md-8 col-md-offset-2 text-center">
            <h1>
            Mission
            </h1>
            <p>
            The mission of this project is to help bring free tutorship 
            and mentorship to racially and economically disadvantaged 
            communities in New Jersey. Racial minority communities underperform 
            in academics due to historical as well as current disadvantageous 
            policy making here in the Garden State. Dedicated tutoring and mentorship 
            can help make a huge impact on students’ academic success.
            </p>
        </div>
    </div>

    <div class = "row text-center">
        <h1>
            How Tutoring and Mentorship Can Be Impactful
        </h1>
        <div class = "col-md-2 col-md-offset-2">
            <p>
            -Name 1
            </p>
        </div>
        <div class = "col-md-2 col-md-offset-1">
            <p>
            -Name 2
            </p>
        </div>
        <div class = "col-md-2 col-md-offset-1">
            <p>
            -Name 3
            </p>
        </div>
    </div>

    <div class = "row">
        <div class = "col-md-8 col-md-offset-2 text-center">
            <h1>
            Goals
            </h1>
            <p>
            [vid goes here]
            </p>
        </div>
    </div>
</div>

<%= render "devise/shared/style" %>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag "application" %>
    <%= stylesheet_pack_tag "application" %>
  </head>

  <body class="container">
    <% if notice.present? %>
      <aside class="alert alert-info">
        <%= notice %>
      </aside>
    <% end %>
    <% if alert.present? %>
      <aside class="alert alert-danger">
        <%= alert %>
      </aside>
    <% end %>
    <%= yield %>
  </body>
</html>

src/app/views/loginpage/index.html.erb
<!-- test for authentication -->
<header>
    <h1>
        LEO login page, <%= current_user.email %>
    </h1>
</header>
<section>
    <p>
        This is the login page for LEO
    </p>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</section>

src/app/views/post/_post.html.erb
<!-- post format, in modal form for use in modal  -->

<form>
    <div class="form-group">
        <label>Title</label>
        <input type="email" class="form-control" placeholder="type title here ...">
    </div>
    
    <div class="form-group">
        <label>Question</label>
        <textarea class="form-control" rows="5" placeholder="type question here ..."></textarea>
    </div>
    
    <div class="form-group">
        <label>Subject</label>
        <select class="form-control">
            <option>Chemistry</option>
        </select>
    </div>
</form>

src/app/views/post/list.html.erb
<!-- format for listing all posts (for future use in subjects page)-->
<% if @posts.blank? %>
    <p>my questions...</p>
<% else %>
    <ul id = "posts">
    <% @posts.each do |c| %>
    <li><%= link_to c.title, {:action => 'show', :id => c.id} -%></li>
    <li><%= link_to c.entry, {:action => 'show', :id => c.id} -%></li>
    <% end %>
    </ul>

<% end %>

<p><%= link_to "Go To My Page", studentpage_path %></p>

src/app/views/post/new.html.erb
<!-- post format, in new page form for use in new page-->

<h1>Post Question</h1>

<%= form_tag :action => 'create' do %>

    <p><label for = "post_title">Title</label>:
    <%= text_field 'posts', 'title' %></p>

    <p><label for = "post_entry">Question</label><br/>
    <%= text_area 'posts', 'entry' %></p>

    <p><label for = "post_subject">Subject</label>:
    <%= collection_select(:posts, :subject, @subjects, :id, :name, prompt: true) %></p>

    <%= submit_tag "Post" %>

<% end -%>

<p><%= link_to "Go To My Page", studentpage_path %></p>

src/app/views/studentpage/_navbar.html.erb
<!-- nav bar for student page -->

<nav class="navbar align-right">
    <!-- botton for notifications -->
    <button type="button" class="btn btn-default navbar-btn btn-lg">Notifications</button>
    <div class="divider"></div>
    
    <!-- botton for groups -->
    <button type="button" class="btn btn-default navbar-btn btn-lg">Groups</button>
    <div class="divider"></div>

    <!-- botton dropdown to select subjects (for future use with subjects page) -->
    <div class="btn-group">
        <button class="btn dropdown-toggle btn-default btn-lg" type="button" id="menu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Subject <span class="caret"></span></button>
        <ul class="dropdown-menu" aria-labelledby="menu1">
            <li><%= link_to 'Chemistry', list_path %></li>
            <li class="disabled"><%= link_to 'Math', homepage_path %></li>
            <li class="disabled"><%= link_to 'Computer Science', homepage_path %></li>          
        </ul>
    </div>
    <div class="divider"></div>
    
    <!-- button to make a post (redirects to new page to make post) -->
    <%= link_to 'Post Question', new_path,  :class => "btn btn-primary btn-lg" %>
</nav>

<! -- use bootstrap modal to ask questions-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

src/app/views/studentpage/index.html.erb
<!-- format for student page-->

<div class="container">
    <!-- student logo icon-->
    <div class="row">
        <div class = "col-md-2 col-md-offset-1 text-center">
            <div class = "wrap-sp-user">
                <span class="glyphicon-big glyphicon glyphicon-pencil" aria-hidden="true"></span>
                <p>
                    </br>
                    <!-- displays students email-->
                    <%= current_user.email %>
                </p>
                <!-- logout button -->
                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </div>
        </div>

        <!-- format for previewing questions made by student user -->
        <div class = "wrap-sp-nav col-md-6">
            <%= render "navbar" %>
            <div class = "wrap-sp-questions">
                <!-- (add a preview to list of posts) -->
            </div>    
        </div>
    </div>

    <!-- back to home button format -->
    <div class="row">
        <div class="wrap-bottom col-md-2 col-md-offset-5 text-center">
            <p>Go To <%= link_to 'Home', homepage_path %></p>
        </div>
    </div> 

</div>

<%= render "devise/shared/style" %>